language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
cache: pip
sudo: false
env:
  matrix:
    - TOX_ENV=py35
    - TOX_ENV=py36
    - TOX_ENV=py37
install:
  - pip install cython
  - pip install tox
script:
  - tox -e $TOX_ENV
after_script:
  - cat .tox/$TOX_ENV/log/*.log
