language: python
cache: pip
sudo: false
matrix:
  include:
    - python: 3.5
      eng: TOX_ENV=py35
    - python: 3.6
      eng: TOX_ENV=py36
    - python: 3.7
      eng: TOX_ENV=py37
    - python: 3.8
      eng: TOX_ENV=py38
install:
  - pip install cython
  - pip install tox
script:
  - tox -e $TOX_ENV
after_script:
  - cat .tox/$TOX_ENV/log/*.log
