name: build wheels for linux

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build wheels
        uses: ./.github/actions/build-manylinux
      - name: upload wheels
        uses: actions/upload-artifact@v1
        with:
          name: dist_linux
          path: wheelhouse
